### ISSUE TITLE
Could you provide your  mini imagenet split file

### ISSUE THREAD

**Issue by tonysy** [eleniTriantafillou/few_shot_mAP_public#1]
Could you provide your  mini imagenet split .csv file? Thanks a lot

**Comment by eleniTriantafillou** [comment]
I'm using the mini imagenet splits defined here: https://github.com/twitter/meta-learning-lstm/blob/master/data/miniImagenet/

**Comment by tonysy** [comment]
Thanks a lot, however, I cannot find the mapping between their split file and the ImageNet dataset name, could you share this mapping?

**Comment by eleniTriantafillou** [comment]
Yeah, these splits refer to file names of the version of mini-ImageNet used in this paper: https://openreview.net/pdf?id=rJY0-Kcll. You would need to email Sachin Ravi (the first author of that paper) to request access to this version of the dataset.

**Comment by tonysy** [comment]
@eleniTriantafillou  Hi, thanks for your reply. But I have sent email to Ravi, got no response. Could your share the details of this mapping. Thanks a lot.

**Comment by eleniTriantafillou** [comment]
I can not, you have to obtain this data from Ravi&Larochelle. Sorry about that.
