### ISSUE TITLE
 omniglot split file

### ISSUE THREAD

**Issue by sim-san** [eleniTriantafillou/few_shot_mAP_public#2]
Hi,
thanks for your code.
Could you provide your omniglot split .txt files?
This will help us a lot to understand your code.
Simon

**Comment by eleniTriantafillou** [comment]
Hi Simon,
Sorry for the delay - the omniglot split files are now posted under data/dataset_splits/omniglot
Thanks for your interest!
Eleni

**Comment by sim-san** [comment]
Thanks a lot
